### ISSUE TITLE
tlrc now available as a NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [acuteenvy/tlrc#31]
FYI, I've packaged `tlrc` for NetBSD and merged the package into the main branch.
Commit log for reference, https://mail-index.netbsd.org/pkgsrc-changes/2023/08/18/msg280871.html

**Comment by acuteenvy** [comment]
Thank you for packaging. I'm not very familiar with NetBSD, but I've tried installing `tlrc` with `pkgin`, and it tells me that the package doesn't exist:

```
# pkgin install tlrc
tlrc is not available in the repository
calculating dependencies...done.
nothing to do.
```

Are packages added only along with a new release?

**Comment by 0323pin** [comment]
> I've tried installing tlrc with pkgin, and it tells me that the package doesn't exist

That's correct, it only exists in current. Stable branches are cut 4 times per year. So, it will be available on the 2023Q3 branch which, should be cut at the end of September.

> Are packages added only along with a new release?

No, releases do not impact packages in general, only those that are a part of the base system.

But, here it is running on my system,

![2023-08-19-203521_1366x768_scrot](https://github.com/acuteenvy/tlrc/assets/90570748/80ddcd7f-df96-489e-bc04-8d2e86c362c1)

I use NetBSD-current and pkgsrc-current, both are update daily.

**Comment by acuteenvy** [comment]
Thank you for explaining, I'll add NetBSD installation instructions to the README.
